name: omnisaude_chatbot_example
description: Demonstrates how to use the omnisaude_chatbot plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  rx_notifier: ^0.0.8
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1

  flutter:
    sdk: flutter

  omnisaude_chatbot:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
