name: omnisaude_chatbot
description: Pacote de integração do chatbot para aplicativos móveis e sistemas Web.
version: 0.0.6-dev.2+2
homepage: "https://www.omnisaude.co/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter_modular: ^3.0.0-nullsafety.36

  mime: ^0.9.7
  rx_notifier: ^0.0.8
  path: ^1.7.0

  intl: ^0.17.0-nullsafety.2
  photo_view: ^0.10.3
  flutter_html: ^1.1.1
  url_launcher: ^5.7.10
  path_provider: ^1.6.24
  carousel_slider: ^2.3.1
  flutter_slidable: ^0.5.7
  agora_rtc_engine: ^3.2.1
  web_socket_channel: ^1.1.0
  cached_network_image: ^2.5.0
  flutter_datetime_picker: ^1.4.0
  mask_text_input_formatter: ^1.2.1
  flutter_staggered_grid_view: ^0.3.3

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+2
  build_runner: ^1.10.2

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/avatar/
    - assets/shared/

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
