name: omnisaude_chatbot
description: Pacote de integração do chatbot para aplicativos móveis e sistemas Web.
version: 0.0.5
author: leonardobido.me
homepage: "https://www.omnisaude.co/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^3.0.0-nullsafety.20

  mime: ^0.9.7
  intl: ^0.17.0-nullsafety.2
  photo_view: ^0.10.2
  file_picker: ^2.1.4
  flutter_html: ^1.1.1
  path_provider: ^1.6.18
  universal_html: ^1.2.3
  image_picker: ^0.6.7+17
  carousel_slider: ^2.3.1
  flutter_slidable: ^0.5.7
  agora_rtc_engine: ^3.1.5
  web_socket_channel: ^1.1.0
  cached_network_image: ^2.4.1
  shared_preferences: ^0.5.12+4
  flutter_datetime_picker: ^1.4.0
  flutter_cached_pdfview: ^0.2.3+4
  mask_text_input_formatter: ^1.1.0
  flutter_staggered_grid_view: ^0.3.3
  url_launcher: ^5.7.10


  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+2
  build_runner: ^1.10.2

  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: 'assets/shared/logo/appstore.png'
  image_path_android: 'assets/shared/logo/playstore.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/avatar/
    - assets/shared/

  plugin:
    platforms:
      android:
        package: com.leobidoous.omnisaude.omnisaude_chatbot
        pluginClass: OmnisaudeChatbotPlugin
      ios:
        pluginClass: OmnisaudeChatbotPlugin

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
