name: omnisaude_chatbot
description: Pacote de integração do chatbot para aplicativos móveis e sistemas Web.
version: 0.0.2
author: leonardobido.me
homepage: "https://www.omnisaude.co/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^2.0.1

  photo_view: ^0.10.2
  file_picker: ^2.0.7
  universal_html: ^1.2.3
  image_picker: ^0.6.7+11
  path_provider: ^1.6.18
  carousel_slider: ^2.3.1
  flutter_slidable: ^0.5.7
  web_socket_channel: ^1.1.0
  shared_preferences: ^0.5.12
  cached_network_image: ^2.3.2+1
  flutter_datetime_picker: ^1.4.0
  mask_text_input_formatter: ^1.1.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+2
  build_runner: ^1.10.2

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/avatar/
    - images/shared/


  plugin:
    platforms:
      android:
        package: com.leobidoous.omnisaude.omnisaude_chatbot
        pluginClass: OmnisaudeChatbotPlugin
      ios:
        pluginClass: OmnisaudeChatbotPlugin
